### PR TITLE
Make CI run tests and code check

### PR DESCRIPTION
**Pull request by bauerj**
This adds a [Github Action](https://github.com/features/actions) that runs a few sanity checks against the code on each commit:

- the i18n_extension test suite should pass
- the code should adhere to the [Flutter recommended style](https://dart.dev/guides/language/effective-dart/style)
- static code analysis through `flutter analyze` passes

This makes it easier to spot issues in pull requests like the one with Windows line endings I had a while ago.

I had to raise the required version of the `args` library because `flutter analyze` complained about its non null-safety. So I guess the CI system already paid off 🧤

### CODE REVIEW

**Comment by marcglasberg** [comment]
@bauerj  Hey Johann, could you please disable that "the code should adhere to the Flutter recommended style"? I think their style is quite bad in a lot of ways, and also feel that forcing a single style removes important freedoms. I am ok with the tests passing and static code analysis. Question: Will this just apply the analysis_options.yaml file inside of i18n_extension?

**Comment by bauerj** [comment]
> could you please disable that "the code should adhere to the Flutter recommended style"?

Sure thing, I've done that!

> I think their style is quite bad in a lot of ways, 

Well, the current code already adheres to those guidelines so I'll just assume the bad ways don't show here 😜

> and also feel that forcing a single style removes important freedoms.

I agree with that statement but I think that the Flutter code style is well balanced in that regard. After all, you probably wouldn't want to merge code that looked too weird either. Anyway, I get that it can be annoying if you have to "fix" code that's not actually broken, just formatted differently.

> Question: Will this just apply the analysis_options.yaml file inside of i18n_extension?

Yes, the step where `flutter analyze` is run will respect those settings.

**Comment by bauerj** [comment]
Regarding the issue with updating `args` you mentioned:

We could either leave this PR open until they release the next stable version. But if I understood the issue you linked correctly, that would take months.

I could also add a `// ignore: import_of_legacy_library_into_null_safe` comment in front of the offending line in `bin/getstrings.dart` so this will not be reported until it's possible to update `args`. What do you think?

**Comment by marcglasberg** [comment]
We have to wait. Lots of people won't be able to use i18n_extension anymore if we upgrade, it's not just a question of ignoring the warnings. Lot's of people already can't, because of the analyzer that also conflicts with flutter_driver. Yes, it could take months, but that was a bad Google decision and we have to live with it. I want to keep all dependecies as low as possible until this issue is resolved, even if that's not a perfect solution either.

**Comment by marcglasberg** [comment]
> Well, the current code already adheres to those guidelines so I'll just assume the bad ways don't show here.

For example, I like 100 lines, and "pub points" penalizes all my packages for that reason. Also I like using `_` in names, and it's not allowed.

**Comment by bauerj** [comment]
> We have to wait. Lots of people won't be able to use i18n_extension anymore if we upgrade, it's not just a question of ignoring the warnings.

Yes, I wanted to propose keeping it at the current version and using the comment to suppress the warning.

**Review by marcglasberg — APPROVED** [review]

**Pull request merged**
