### PR TITLE
Issue #120: add support for markForI18n

### PR DESCRIPTION
**Pull request by MarcVanDaele90**
Thanks https://github.com/bauerj for the [link](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/).  This was really useful.
 
First, I created a simple test case (which failed) and then I made the (indeed trivial) changes to make the test case succeed.

### CODE REVIEW

**Comment by bauerj** [comment]
Hi @MarcVanDaele90,

thank you very much for raising this pull request. And congratulations for your first open-source contribution! 🥳

The code change looks good to me. But let's see what @marcglasberg thinks about it 🙂

You already added a test case, that's great! Can you also write a few sentences on how to use it for the [README](https://github.com/marcglasberg/i18n_extension/blob/master/README.md#the-getstrings-exporting-utility)? Users probably also need to change their i18n.dart to include something like `String get markForI18n => this;`. This needs to be explained in the README.

**Comment by MarcVanDaele90** [comment]
I think there is an issue with my fix/solution:  If we just mark it with `markForI18n`, you don't know how it should be translated (normal or as plural) I guess, right?

**Comment by marcglasberg** [comment]
@MarcVanDaele90 @bauerj I don't have time to check this now, so what @bauerj decides is good for me.

@bauerj Please let me know if/when I should merge this.

**Comment by bauerj** [comment]
> I think there is an issue with my fix/solution: If we just mark it with markForI18n, you don't know how it should be translated (normal or as plural) I guess, right?

My understanding was that `markForI18n` simply keeps the original string so that:

```
"Apple".markForI18n == "Apple"
"Apple".markForI18n.plural(10) == "Äpfel"
"Apple".markForI18n.i18n == "Apfel"
```

Wouldn't this work?

**Comment by MarcVanDaele90** [comment]
Well, I intended to use the `markForI18n` in my datalayer
```
objects = [{"name": "car".markForI18n, "image":"car.png"}, {"name": "apple".markForI18n, "image":"apple.png"}, ...]
```
and translate it when I use this object in the presentation layer (UI)
```
"How many %s do you see".i18n.fill([object.name.plural(100)]  //here I want to use the plural
```
But `getstrings` collects the strings from the markFor18n and there is no information that it will be used (later, in the UI) for plurals so the generated `.pot` file will not contain this information I guess.

I'll give it some more thoughts. I would suggest to ignore this 'fix' and to close issue #120  for now.

**Comment by bauerj** [comment]
I see.

Indeed, this seems to render the proposed fix impossible 😞 

Please close the PR then.

**Pull request closed without merging**
